# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'go_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GoWindow(object):
    def setupUi(self, GoWindow):
        GoWindow.setObjectName("GoWindow")
        GoWindow.resize(1300, 1000)
        GoWindow.setMinimumSize(QtCore.QSize(1300, 1000))
        GoWindow.setMaximumSize(QtCore.QSize(1300, 1000))
        GoWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(GoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.chessboard = QtWidgets.QWidget(self.centralwidget)
        self.chessboard.setGeometry(QtCore.QRect(0, 0, 1000, 1000))
        self.chessboard.setStyleSheet("border-image: url(:/bg/image/chessboard.png);")
        self.chessboard.setObjectName("chessboard")
        self.ChessCan = QtWidgets.QWidget(self.centralwidget)
        self.ChessCan.setGeometry(QtCore.QRect(1030, 610, 220, 220))
        self.ChessCan.setStyleSheet("border-image: url(:/bg/image/blacks-removebg-preview.png);")
        self.ChessCan.setObjectName("ChessCan")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(1020, 410, 231, 131))
        self.textBrowser.setStyleSheet("background-color: rgba(255, 255, 255, 150);")
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1060, 420, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1030, 450, 111, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1030, 480, 161, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(240, 239, 521, 191))
        font = QtGui.QFont()
        font.setPointSize(90)
        self.result_label.setFont(font)
        self.result_label.setText("")
        self.result_label.setObjectName("result_label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1030, 510, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(1020, 140, 231, 191))
        self.textBrowser_2.setStyleSheet("background-color: rgba(255, 255, 255, 150);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.yeildBtn = QtWidgets.QPushButton(self.centralwidget)
        self.yeildBtn.setGeometry(QtCore.QRect(1050, 200, 71, 28))
        self.yeildBtn.setObjectName("yeildBtn")
        self.restartBtn = QtWidgets.QPushButton(self.centralwidget)
        self.restartBtn.setGeometry(QtCore.QRect(1050, 240, 71, 28))
        self.restartBtn.setObjectName("restartBtn")
        self.retractBtn = QtWidgets.QPushButton(self.centralwidget)
        self.retractBtn.setGeometry(QtCore.QRect(1150, 200, 71, 28))
        self.retractBtn.setObjectName("retractBtn")
        self.storeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.storeBtn.setGeometry(QtCore.QRect(1050, 280, 71, 28))
        self.storeBtn.setObjectName("storeBtn")
        self.loadBtn = QtWidgets.QPushButton(self.centralwidget)
        self.loadBtn.setGeometry(QtCore.QRect(1150, 280, 71, 28))
        self.loadBtn.setObjectName("loadBtn")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1080, 160, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.giveuptBtn = QtWidgets.QPushButton(self.centralwidget)
        self.giveuptBtn.setGeometry(QtCore.QRect(1150, 240, 71, 28))
        self.giveuptBtn.setObjectName("giveuptBtn")
        GoWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(GoWindow)
        QtCore.QMetaObject.connectSlotsByName(GoWindow)

    def retranslateUi(self, GoWindow):
        _translate = QtCore.QCoreApplication.translate
        GoWindow.setWindowTitle(_translate("GoWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("GoWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10.8pt;\"><br /></p></body></html>"))
        self.label.setText(_translate("GoWindow", "围棋（双人对战）"))
        self.label_2.setText(_translate("GoWindow", "步数：0"))
        self.label_3.setText(_translate("GoWindow", "时间：00:00"))
        self.label_4.setText(_translate("GoWindow", "当前棋手：黑棋"))
        self.textBrowser_2.setHtml(_translate("GoWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10.8pt;\"><br /></p></body></html>"))
        self.yeildBtn.setText(_translate("GoWindow", "认输"))
        self.restartBtn.setText(_translate("GoWindow", "重新开始"))
        self.retractBtn.setText(_translate("GoWindow", "悔棋"))
        self.storeBtn.setText(_translate("GoWindow", "保存棋局"))
        self.loadBtn.setText(_translate("GoWindow", "导入棋局"))
        self.label_5.setText(_translate("GoWindow", "用户可选操作"))
        self.giveuptBtn.setText(_translate("GoWindow", "弃一手"))
import chess_qrc_rc
