# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartWindow(object):
    def setupUi(self, StartWindow):
        StartWindow.setObjectName("StartWindow")
        StartWindow.resize(453, 242)
        self.centralwidget = QtWidgets.QWidget(StartWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(170, 150, 93, 28))
        self.startButton.setObjectName("startButton")
        self.combBox = QtWidgets.QComboBox(self.centralwidget)
        self.combBox.setGeometry(QtCore.QRect(100, 90, 87, 22))
        self.combBox.setObjectName("combBox")
        self.combBox.addItem("")
        self.combBox.addItem("")
        self.label_chess = QtWidgets.QLabel(self.centralwidget)
        self.label_chess.setGeometry(QtCore.QRect(100, 70, 45, 15))
        self.label_chess.setObjectName("label_chess")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(40, 30, 381, 161))
        self.textBrowser.setStyleSheet("background-color: rgba(255, 255, 255, 150);")
        self.textBrowser.setObjectName("textBrowser")
        self.sizeInput = QtWidgets.QLineEdit(self.centralwidget)
        self.sizeInput.setGeometry(QtCore.QRect(250, 90, 121, 21))
        self.sizeInput.setObjectName("sizeInput")
        self.label_size = QtWidgets.QLabel(self.centralwidget)
        self.label_size.setGeometry(QtCore.QRect(250, 70, 121, 16))
        self.label_size.setObjectName("label_size")
        self.textBrowser.raise_()
        self.startButton.raise_()
        self.combBox.raise_()
        self.label_chess.raise_()
        self.sizeInput.raise_()
        self.label_size.raise_()
        StartWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StartWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 453, 26))
        self.menubar.setObjectName("menubar")
        StartWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StartWindow)
        self.statusbar.setObjectName("statusbar")
        StartWindow.setStatusBar(self.statusbar)

        self.retranslateUi(StartWindow)
        QtCore.QMetaObject.connectSlotsByName(StartWindow)

    def retranslateUi(self, StartWindow):
        _translate = QtCore.QCoreApplication.translate
        StartWindow.setWindowTitle(_translate("StartWindow", "MainWindow"))
        self.startButton.setText(_translate("StartWindow", "开始游戏"))
        self.combBox.setCurrentText(_translate("StartWindow", "五子棋"))
        self.combBox.setItemText(0, _translate("StartWindow", "五子棋"))
        self.combBox.setItemText(1, _translate("StartWindow", "围棋"))
        self.label_chess.setText(_translate("StartWindow", "棋类："))
        self.textBrowser.setHtml(_translate("StartWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10.8pt;\"><br /></p></body></html>"))
        self.label_size.setText(_translate("StartWindow", "棋盘大小(8-19):"))
